### PR TITLE
Set versions of app and notebook

### PR DESCRIPTION
**Pull request by toch**
- app 0.74.7
- notebeook 1.4.5

jupyter hub is already set to local-2024.11.15

### CODE REVIEW

**Comment by toch** [comment]
as the latest "release" tag for the frontend is one month old, I didn't know what to use. Should I use that one?

**Review by nazarfil — APPROVED** [review]

**Comment by qgerome** [comment]
> as the latest "release" tag for the frontend is one month old, I didn't know what to use. Should I use that one?

Yes you can set the latest release of the frontend.

**Comment by toch** [comment]
to be sure, we're talking about 0.54.2 right?

https://hub.docker.com/layers/blsq/openhexa-frontend/0.54.2/images/sha256-f4885e9a107bd3a6856d76d3ce5a5daa51d96f4c9d7af4454f1f1a9a6510590e?context=explore

**Comment by qgerome** [comment]
Yes this is the latest one.

**Comment by toch** [comment]
I had some issues locally, but probably due to a mixup between several deployments. After having cleaned everything, tests passed (Have I told you that I like the smoke tests very much?).

So should be ok with GA.

**Pull request merged**
